### PR TITLE
Fix #162 - Add showNegativeScheduledArrivals option to data-sources.xml

### LINKED ISSUE #162: Per stop predictions - scheduled times may be shown if a GTFS-rt producer aggressively drops predictions
We're seeing this issue when testing in Tampa with a GTFS-rt feed with multiple `StopTimeUpdates` per trip.  The GTFS-rt producer is very aggressive in dropping `StopTimeUpdates` - as soon as the vehicle passes the stop, the `StopTimeUpdate` disappears from the GTFS-rt feed.

The resulting UX is that the user sees real-time info as the bus approaches the stop, but then it flashes to scheduled time just as the bus arrives/departs (e.g., it shows negative scheduled arrivals).

We’re working on a patch that would fix the scenario for late/on time arrivals – the resulting behavior with the patch is that negative scheduled times would never be shown if `<property name="showNegativeArrivals" value="false" />` is set in `data-sources.xml` for an agency.  

The WIP PR for this issue is https://github.com/OneBusAway/onebusaway-application-modules/pull/160.

However, the early arrivals are a problem – with the GTFS-rt feed is currently dropping early arrivals before the bus is scheduled to have passed the stop – the end result is that we show real-time info until the bus passes the stop, but then the ETA bounces back up to the scheduled time and we count down the scheduled ETA until the scheduled time is past.  There’s no way to fix this on the consumer end without violating the GTFS-rt spec, so we’re trying to get the GTFS-rt language clarified for the producer requirements.

I've opened a GTFS-rt proposal to clarify this language, and require producers to keep predictions in the feed until *after* the scheduled arrival time for that stop (from GTFS stop_times.txt) has passed.

If you're so inclinded, please vote for this GTFS-rt proposal at https://github.com/google/transit/pull/16.

cc @sheldonabrown @cagryInside

### PR DESCRIPTION
**Pull request by cagryInside**
I have implemented `showNegativeScheduledArrivals` option in `data-soruces.xml`.  Now we can set the property:

```
  <property name="showNegativeScheduledArrivals" value="false" />
```

It set default `true` if a user never sets `showNegativeScheduledArrivals` property.

cc @barbeau

### CODE REVIEW

**Comment by barbeau** [comment]
@cagryInside Does this hide all negative arrivals (schedule and real-time times), or just negative arrivals for scheduled times when real-time isn't available?  For the PSTA situation (which I still need to open an issue with an explanation for), we want to show negative arrivals for real-time data, but not for schedule data.  So, we should only hide negative arrivals when no real-time info is available.

**Comment by barbeau** [comment]
On a related note, we should also probably rename the property to `showNegativeScheduledArrivals`.

**Comment by cagryInside** [comment]
@barbeau Yes this improvement hides all negative arrivals. 
I check the negative arrivals by looking at the `numberOfStopsAway` property. Now, I should also check `predictedArrivalTime`. For example:

```
      if(!isNegativeArrivalsEnabled(instance.getBlockTrip().getTrip().getId().getAgencyId())
          && bean.getNumberOfStopsAway() < 0 && bean.getPredictedArrivalTime() <= 0)

```

But I am not sure this is the best approach the check `predictedArrivalTime`. Can we discuss this sometime this week?

**Comment by barbeau** [comment]
Yes, let's discuss this week.

**Comment by barbeau** [comment]
Per our discussion, `bean.getPredictedArrivalTime() <= 0` is a good indicator of whether or not real-time info exists, so that portion looks fine.

**Comment by barbeau** [comment]
We're doing some final tests to make sure that `bean.getNumberOfStopsAway() < 0` is a good indicator of whether or not the arrival is scheduled to have occurred in the past.  If so, then everything should be working correctly.  If not, we'll need to come up with another implementation to check if the scheduled time (arrival or departure, depending on the `stop_sequence`) is in the past.

**Comment by barbeau** [comment]
The issue describing the problem this PR addresses is https://github.com/OneBusAway/onebusaway-application-modules/issues/162.

**Comment by barbeau** [comment]
This patch is currently deployed to http://app.staging.obahart.org/ for the agency PSTA:
http://app.staging.obahart.org/where/standard/stop.action?id=PSTA_4025

**Comment by barbeau** [comment]
@sheldonabrown I believe this should be ready for review.  We've been testing it with PSTA and it seems to be working as intended.

**Comment by sheldonabrown** [comment]
Merged this into camsys/unified branch, with intent to later merge camsys/unified to onebusaway/master

**Comment by aaronbrethorst** [comment]
no action in 8 years. closing.

**Pull request closed without merging**
