### PR TITLE
2.0.39 merge

### PR DESCRIPTION
**Pull request by sheldonabrown**
Merging in bug fixes from camsys repo

### CODE REVIEW

**Comment by barbeau** [comment]
:tada:

**Comment by AlexKven** [comment]
I'm curious what makes service date filtering necessary on get stops for route. It partially breaks the "show route" function on the app, and threw me off as a user of the API.

**Comment by barbeau** [comment]
@AlexKven IIRC because the stops for a particular route/trip can vary depending on the day of week / date.

**Comment by AlexKven** [comment]
I get why that is a problem, but IMO this isn't a good way to solve the problem. It just makes the app work differently depending on the day. For example, if I want to plan a future trip and I want to see the stops for a weekday-only route, I can't do that on the weekend (and the error message shown is very confusing for regular users):
image

Whereas some routes (like King County Metro 255) have different variations within the day, and the app still shows all three variations of the route at once, and doesn't really help the user figure out which ones their bus goes to:
image

I don't really have any ideas for how to solve this issue easily. I think this date filtering could be useful, but it should be off by default and enabled with a query parameter.

**Comment by barbeau** [comment]
@AlexKven Feel free to open an issue on the API in this repo, and on onebusaway-android for UI issues there!

**Pull request merged**
