### PR TITLE
Documentation fixes

### PR DESCRIPTION
**Pull request by lorainekv**
Updated these two documentation pages to include valid IDs so that the sample calls wouldn't return 404.

Updated the sample responses to reflect current responses.

### CODE REVIEW

**Comment by lorainekv** [comment]
Hello! I recently received an API key to use the API, noticed that some of the sample calls include invalid params. I haven't gone through other methods aside from "routes" and "stops-from-route", so it's possible that other method sample calls are outdated / invalid too.

**Comment by barbeau** [comment]
@lorainekv Thanks!  Could you please sign the [ICLA](https://docs.google.com/forms/d/12jV-ByyN186MuPotMvxJtNKtSaGGTnEHm8rXomM2bm4/viewform)?

**Comment by barbeau** [comment]
ICLA manually confirmed :+1:

**Comment by barbeau** [comment]
Thanks @lorainekv!

**Pull request merged**
