### PR TITLE
Fix #109 - Add Travis CI builds for pull requests

### LINKED ISSUE #109: Add CI builds for pull requests
It would be useful to run CI builds for new pull requests to confirm that the PR builds and passes all tests before its reviewed.  AFAICT, our current [ci.onebusaway.org](http://ci.onebusaway.org/) build server does not build PRs, and does not display results within the Github PR page.

We've been using [Travis CI](https://travis-ci.org/) for all CI builds (including PRs) for [OBA iOS](https://travis-ci.org/OneBusAway/onebusaway-iphone) and [OBA Android](https://travis-ci.org/OneBusAway/onebusaway-android) for a while, and it works fairly well.  It also includes direct integration for displaying the CI build result within the Github PR.  It also rebuilds on every new push to the PR branch, so you can continously monitor the status of the PR prior to review/merge.

For example, here's a PR that's failed a build/test:

image

...and here's one that's passing build/tests:

image

You can also click on the Travis CI link and it will take you straight to the web interface for the corresponding CI build.

I propose that we leave ci.onebusaway.org as-is, but set up Travis CI to build pull requests on this project.  I'd be happy to set this up, which involves configuring Travis CI for Github hooks, and adding a `.travis.yml` file to the root of this project that contains the script to be executed on Travis.  I've set this up for other Java server projects that use Maven, and its fairly straightforward.

@sheldonabrown is it possible to configure the existing ci.onebusaway.org server to build Github PRs as well?  If so, is that a direction that you'd prefer?

### PR DESCRIPTION
**Pull request by barbeau**

### CODE REVIEW

**Comment by sheldonabrown** [comment]
Jenkins bump

**Comment by barbeau** [comment]
@sheldonabrown any objections to merging this?  To my knowledge there aren't any downsides.  And its easily removed if we want to stop building PRs on Travis at any point.

**Comment by barbeau** [comment]
Not hearing any objections, I'm going to merge this.  It gives us another reference for builds, specifically PRs, and there aren't any known downsides.

**Comment by sheldonabrown** [comment]
Thanks Sean -- I was meaning to take a closer look but didn't get a chance.

Yes -- no objections here.

**Pull request merged**
