### PR TITLE
Unified merge

### PR DESCRIPTION
**Pull request by sheldonabrown**
This representing pulling in all the improvements from the Cambridge Systematics repository.  To summarize, they include:

**New Features:**
**onebusaway-admin-webapp:** a back-end management module that builds bundles, manages users and API keys, and many other administrative functions (some that are very agency specific).
**onebusaway-enterprise-acta-webapp:** a sample branded web application based off of the MTA Bus Time code base
**onebusaway-gtfs-archiver:** basic support for archiving GTFS and GTFS-RT do a database
**onebusaway-twilio-webapp:**  a trivial port of the onebusaway-phone-webapp to Twilio (cloud) services
**onebusaway-nextbus-api:** an alternate implementation of the nextbus API using transitime

**Improvements:**
- many many bug fixes
- true per-stop prediction support via TimePointRecords
- many more metrics in onebusaway-watchdog
- enhanced user indices for additional API key metadata
- Spring 3 security updates

**Removed:**
- OTP trip planning (via Kurt's pull request).

Although this is a massive pull request, the bulk of it represents new modules.  I have performed a quick first pass at testing of:
onebusaway-transit-data-federation-webapp
onebusaway-api-webapp
onebusaway-webapp

and verified they still work.  I hope to test more as time allows.

**EDIT**

Here are some instructions for getting this branch up and running:
https://github.com/OneBusAway/onebusaway-application-modules/wiki/Enterprise-Webapp-Configuration

### CODE REVIEW

**Comment by barbeau** [comment]
@sheldonabrown This is awesome!  Glad to see it coming back to the main OBA repo.

So does this support real-time per-stop predictions as well as real-time updates for frequency-based (`exact_times=0` and exact_times=1`) trips?

**Comment by sheldonabrown** [comment]
I just sent this to the developer mailing list:
TO: onebusaway-dev
Subject: Camsys pull request
I did a summary merge of all the goodies from the Cambridge Systematics repository:

https://github.com/OneBusAway/onebusaway-application-modules/pull/176

As the pull requests states, although its a very large set of changes, the majority of the changes are additions and entirely new modules.  Some of the bundle models have been changes as well, requiring a bundle re-build.

I'd appreciate multiple sets of eyes on the pull request, and appreciated any and all feedback.

Some pre-emptive criticsm:

- onebusaway-twilio-webapp was a good idea but its implementation is rough around the edges and could use considerable refactoring.
- onebusaway-nextbus-api-webapp introduces a dependency on transitime.
- onebusaway-admin-webapp has grown quite feature-full but has little to no documentation and has many features that although easily hidden, are very specific to some agencies.
- onebusaway-enterprise-webapp does not implement the full set of features that onebusaway-webapp does, and is not as mode-aware and as agency-agnostic.  With that said, great strides have been made here recently and will continue to progress

As a community, I'd like feedback on whether its worth pulling in these modules "as is" so they can be improved, or perhaps keeping them separate until they mature.

Along those lines, as I've had a number of developers working on the camsys repo throughout the years, coding standards have not been met as strictly as they have been in the OBA repo.  It may be helpful to run a code-style application against the code base if anyone has the time and inclination...

So please, let me know your thoughts,

Sheldon

**Comment by sheldonabrown** [comment]
@barbeau Yes, this has the latest improvements for per-stop predictions, with many bug fixes from recent rollouts.

**Comment by sheldonabrown** [comment]
Some onebusaway-admin-webapp tests are failing that are passing locally.  I'll track that down shortly...

**Comment by sheldonabrown** [comment]
**ci.camys.com** reports the dreaded org.onebusaway.federations.impl.DynamicFederatedServiceCollectionImplTest.test failure.  That one is intermittent and well known, but perhaps now is the time to finally fix it ;)

**travis** is not resolving nexus.codehaus.org, which I hope is a temporary DNS issue as I don't understand how that would have changed.

**Comment by barbeau** [comment]
>travis is not resolving nexus.codehaus.org, which I hope is a temporary DNS issue as I don't understand how that would have changed.

I just kicked Travis to restart the build, hopefully it passes this time.

>onebusaway-nextbus-api-webapp introduces a dependency on transitime.

Could you elaborate on this a bit?  It looks like this exposes an API that follows the NextBus spec (good thing Google won the fair-use argument against Oracle ;) ), but I'm not sure I understand where the dependency on Transitime comes in.  It's not a build-time dependency?

**Comment by barbeau** [comment]
Travis failed again with the same `[WARNING] Could not transfer metadata commons-logging:commons-logging/maven-metadata.xml from/to codehaus-snapshots (https://nexus.codehaus.org/snapshots/): nexus.codehaus.org: Name or service not known`.

On my Windows machine if I do `nslookup nexus.codehaus.org` I get:

~~~
>nslookup nexus.codehaus.org
Server:  nyc.cutr.usf.edu
Address:  131.247.19.33

*** nyc.cutr.usf.edu can't find nexus.codehaus.org: Non-existent domain
~~~

Looks like codehaus hosting was killed?

See http://www.codehaus.org/

**Comment by sheldonabrown** [comment]
Correct, its not a build/compile time dependency.  Its simply that
(currently) the module has no value unless you also deploy transitime.  But
come to think of it there is lots of precedent for that in OBA.

I'd eventually like to rewrite the onebusaway-nextbus-api-webapp to use the
TransitDataService instead of transitime, but that's not a high priority
right now.

Sheldon

**Comment by sheldonabrown** [comment]
@barbeau I've fixed a few issues but now the log file is exceeding 4MB and terminating the build.  Can you turn of verbose (and potentially add --quiet) and re-try travis?

**Comment by barbeau** [comment]
@sheldonabrown Sure, I just pushed https://github.com/OneBusAway/onebusaway-application-modules/commit/f73d86c1ea3fd71ef980df04864f59be69136e86 into this PR, which should run another Travis build with `mvn test -q`.

**Comment by barbeau** [comment]
Alright, just pushed https://github.com/OneBusAway/onebusaway-application-modules/commit/e0bf3a6c148f5f503451856bd20b862444faa492, which should hopefully quiet the install phase on Travis as well.  Build running...

**Comment by sheldonabrown** [comment]
Still no love.  This seems to be a common problem, so we have two options:

1) I can go through an quiet the logging level of some of the worst offenders, but they are legitimate messages you may see while building a bundle
2) we can hack travis via something like:  http://stackoverflow.com/questions/26082444/how-to-work-around-travis-cis-4mb-output-limit/26082445#26082445

**Comment by barbeau** [comment]
@sheldonabrown For 1), is there a way to quiet them only if it's running on Travis?  For example, could we pass a parameter in the Travis `mvn test` that could be read and turn on quiet?

We do something similar with OBA Android to speed up builds only when running on Travis, although that's via Gradle, not Maven.

**Comment by sheldonabrown** [comment]
I could potentially template the log4j setup if you can call travis with a maven profile of "travis".  Let me look into that.

**Comment by barbeau** [comment]
@sheldonabrown Did an introspection API, such as that implemented by @kurtraschke in https://github.com/OneBusAway/onebusaway-application-modules/pull/81, make it into this PR?

If so:

1. What is the endpoint for this?
1. Does it support data from agency [GTFS feed_info.txt](https://developers.google.com/transit/gtfs/reference#feed_infotxt) (in particular, `feed_version`)?

**Comment by sheldonabrown** [comment]
Yes -- not exactly as @kurtraschkey specified because there was a similar
effort that happened in parallel for the NYC codebase.

The endpoint in onebusaway-api-webapp/api/where/config.json?key=<KEY>

It does not support GTFS feed_info.txt, it merely exposes the name and
service date of the bundle.  That's a great idea however.

Sheldon

**Comment by barbeau** [comment]
Thanks @sheldonabrown!

**Comment by barbeau** [comment]
Opened https://github.com/OneBusAway/onebusaway-application-modules/issues/178 specifically for supporting GTFS `feed_info.txt` as part of config API.

**Comment by barbeau** [comment]
@sheldonabrown A Google Group post reminded me of this.  Anything I can do to help get this merged?  IIRC Travis was where we got stalled last time - I really wouldn't want that to be a blocking issue as long as all tests pass locally and on Jenkins (side-note - looks like you got the Github hooks with Jenkins to work?  Cool!).  We can figure out Travis as we go - although looks like there is a conflict now in this PR.

**Comment by danp** [comment]
This could use a rebase / master merge.

**Comment by sheldonabrown** [comment]
Thanks for the poke.  Let me try to get travis passing, and @barbeau and I can discuss what the minimum required to accept the pull request would be.

**Comment by laidig** [comment]
Looking at the Travis log there are a lot of messages such as:
`[INFO] WEB-INF/lib/javax.inject-1.jar already added, skipping`

This is caused by an outdated maven-assembly plugin. updating the version in the obanyc repo stopped this message from gumming up the logs.

**Comment by barbeau** [comment]
For anyone looking at this PR, I believe this is the wiki for instructions for getting it up and running:
Here are some instructions for getting this branch up and running:
https://github.com/OneBusAway/onebusaway-application-modules/wiki/Enterprise-Webapp-Configuration

**Comment by efleisc** [comment]
Unfortunately these instruction don't work.  I get this error with the git clone:
Fatal: Could not read from remote repository

So I downloaded the modules manually,  mvn package works well, but I can't run the app, I always get errors about application-context.xml. This file is not deployed, I can find in the tomcat WEB-INF folder the file: application-cortext-webapp.xml but not this one. If I manually copy this file it complains about another one and so on. I tried running with eclipse, as a service, catalina.sh  Java 7, Java 8 and the problem is always the same.

SEVERE: Exception sending context initialized event to listener instance of class [org.springframework.web.context.ContextLoaderListener]
org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Failed to import bean definitions from URL location [classpath:org/onebusaway/agency_metadata/application-context.xml]
Offending resource: class path resource [org/onebusaway/api/application-context-webapp.xml]; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: IOException parsing XML document from class path resource [org/onebusaway/agency_metadata/application-context.xml]; nested exception is java.io.FileNotFoundException: class path resource [org/onebusaway/agency_metadata/application-context.xml] cannot be opened because it does not exist

**Comment by barbeau** [comment]
@efleisc It looks like there were a few tweaks needed in the wiki to the initial command line statements.  I also added a few links for building bundles there.  I'm somewhat guessing here based on my experience with the existing master branch - hopefully this is close to correct.

You could try it again if you'd like to see if that fixes anything.  Unfortunately I haven't run this myself yet from code so I don't have exact pointers for your specific error.

**Comment by barbeau** [comment]
🎉

**Pull request merged**
