### PR TITLE
Implement API for introspection

### PR DESCRIPTION
**Pull request by kurtraschke**
This PR implements an introspection framework to supply version and instance details, as initially described by @barbeau in onebusaway/onebusaway-application-modules#47.

The end-user-visible changes are as follows:
- new `instance-versions` API method (sample [JSON](https://gist.github.com/kurtraschke/8776180#file-instance-versions-json), [XML](https://gist.github.com/kurtraschke/8776180#file-instance-versions-xml)), which returns full version details for the API server itself as well as the one-or-more TDS instances backing it (note that these could all be different versions)
- new `instance-details` API method (sample [JSON](https://gist.github.com/kurtraschke/8776180#file-instance-details-json), [XML](https://gist.github.com/kurtraschke/8776180#file-instance-details-xml)), which returns a list of TDS instances backing the API server, and, for each TDS instance:
  - Instance name
  - Language
  - Contact email
  - Twitter URL (optional)
  - Facebook URL (optional)
  
  The intent here is to mimic the data model of the multi-region directory, with an eye towards automating registration of instances/eliminating the need for server operators to manually collect data from their instances and copy-paste it into the multi-region directory.

Behind the scenes, there are additional changes:
- a new `IntrospectionService` in `onebusaway-transit-data-federation` which returns the instance details and version information
- two new Web pages served from the TDS, to return the instance state and version, for debugging/setup
- a new `InstanceDetails` class which can be instantiated as a bean in `data-sources.xml` or filled with data from a properties file to specify the instance's details.

I am not entirely satisfied with the XML serialization for the new API methods, but that's dependent on XStream; we are using an older version which does not offer the same options for serializing `Map` instances as the latest version (1.4.6).

In addition, we will need to bump the version of `maven-resources-plugin` in the parent POM; onebusaway/onebusaway#3 has been opened for that.

### CODE REVIEW

**Comment by sheldonabrown** [comment]
Jenkins bump

**Comment by russellhoff** [comment]
@kurtraschke you'd accept licence/cla

**Comment by barbeau** [comment]
Closing and reopening so the CLA bot comments on the PR.   I believe this is superceded by #176, though.

**Comment by barbeau** [comment]
@kurtraschke Do you know if the [watchdog-webapp](https://github.com/OneBusAway/onebusaway-application-modules/wiki/OneBusAway-Watchdog) fully replaces this PR, or is there still stuff in here not in the watchdog-webapp?

**Comment by aaronbrethorst** [comment]
closing since there's been no action in here for six years.

**Pull request closed without merging**
