### PR TITLE
Issue #366: Add an endpoint to retrieve the stops of a particular agency

### PR DESCRIPTION
**Pull request by AngeloAvv**
Adds feature described in #366

### CODE REVIEW

**Comment by aaronbrethorst** [comment]
@AngeloAvv thank you for adding this! Can I ask you to add one or two basic unit tests that exercise the functionality you've added? I'll follow up on this with a full code review soon, and we're actively working on getting new JARs and WARs published!

**Comment by AngeloAvv** [comment]
@aaronbrethorst done!

**Comment by aaronbrethorst** [comment]
@AngeloAvv apologies for the delay. The CI is failing with the error:

> Error:  Failed to execute goal com.mycila:license-maven-plugin:3.0:check (default) on project onebusaway-transit-data-federation: Some files do not have the expected license header -> [Help 1]

**Comment by aaronbrethorst** [comment]
@AngeloAvv I haven't forgotten about you or this PR! Just need to get my development machine set back up to test this. Sorry it's taking so long!

**Review by aaronbrethorst — APPROVED** [review]
Looks good and works great! nice work :)

**Comment by aaronbrethorst** [comment]
Here's the example output for the Unitrans agency in Davis CA for Ahmed. 

[stops-for-agency_unitrans.json](https://github.com/user-attachments/files/16923881/stops-for-agency_unitrans.json)

**Comment by AngeloAvv** [comment]
@aaronbrethorst thank you so much! Do you have an ETA for release 2.5.13? Where can I follow any updates?

**Pull request merged**
