### PR TITLE
Update Maven repos for OBA and Geotools releases

### PR DESCRIPTION
**Pull request by barbeau**
For GeoTools repo, see https://travis-ci.org/github/OneBusAway/onebusaway-application-modules/builds/677735318, opentripplanner/OpenTripPlanner#3039

### CODE REVIEW

**Comment by barbeau** [comment]
Travis build is failing (https://travis-ci.org/github/OneBusAway/onebusaway-application-modules/builds/677745065) with:

>[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.6:single (default) on project onebusaway-transit-data-federation-builder: Execution default of goal org.apache.maven.plugins:maven-assembly-plugin:2.6:single failed: Plugin org.apache.maven.plugins:maven-assembly-plugin:2.6 or one of its dependencies could not be resolved: Could not transfer artifact org.codehaus.plexus:plexus-archiver:jar:3.0.1 from/to google-maven-central (https://maven-central.storage-download.googleapis.com/maven2/): GET request of: org/codehaus/plexus/plexus-archiver/3.0.1/plexus-archiver-3.0.1.jar from google-maven-central failed: Connection reset -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :onebusaway-transit-data-federation-builder
The command "mvn install -Ptravis -DskipTests=true -Dmaven.javadoc.skip=true -Dvalidate.silent=true -Dlog4j.configuration= -B -V -q" failed and exited with 1 during .

**Comment by barbeau** [comment]
Closing and re-opening trigger Travis again. For some reason I can't just restart the job.

**Comment by barbeau** [comment]
Most recent Travis build now passes:
https://travis-ci.org/github/OneBusAway/onebusaway-application-modules/builds/677861958

**Comment by sheldonabrown** [comment]
I've accomplished this via a merge from camsys.  Closing

**Comment by barbeau** [comment]
Thanks @sheldonabrown!

**Pull request closed without merging**
