### PR TITLE
Add "delay" in trip updates

### PR DESCRIPTION
**Pull request by wkulesza**
change causes "delay" to appear in trip updates - only in case it is required

### CODE REVIEW

**Comment by sheldonabrown** [comment]
I have to admit -- I'm a little disappointed.  One missed unit test I can understand, but now I'm not convinced you ever ran the unit tests...

**Comment by sheldonabrown** [comment]
I disagree with this pull request.  OneBusAway uses delay as an instantaneous schedule deviation; it does not contradict the schedule deviations calculated per time point or per stop time update.

The delay field currently directly correlates to the position of the vehicle with respect to the schedule on input data, so it makes sense to pass it through consistently on output as well.

**Comment by barbeau** [comment]
Commenting just on the concept here (not on the code) - I think this PR adds schedule deviation as the experimental field `trip_update.delay` if stop-level delays aren't available?

If so, this is arguably correct given the current somewhat ambiguous definition of [this field](https://github.com/google/transit/blob/master/gtfs-realtime/spec/en/reference.md#message-tripupdate) in the GTFS-realtime spec (although I'm planning on proposing a change to this soon, which would restrict this field to predicted values, not observed schedule deviations).

**Comment by wkulesza** [comment]
@sheldonabrown I only recently saw your replies here - github didn't notify me at all, therefore i missed them. My dev was working on a couple of issues, testing it locally and I need to admit, following conventions wasn't top of the list - these were very time-limited. Trying to get back to those now and make them according to guidelines and hopefully getting them correctly back into the main branch soon.

**Comment by aaronbrethorst** [comment]
no action in 5 years. closing.

**Pull request closed without merging**
